### ISSUE TITLE
如何把图片上传的图片替换到文章中去？

### ISSUE THREAD

**Issue by 529834149** [laravel-admin-extensions/simditor#2]
{
file: "http://knowledge.org/public/uploads/article/afce67bbf5c0732c2e8e382e605bae2a.jpg"
size: 71376
tmp_name: "12"
}
图片上传返回这些信息，如何将 文本域中的图片流替换成我上传的图片

**Comment by jxlwqq** [comment]
具体的配置请看simditor 的官方文档：https://simditor.tower.im/docs/doc-usage.html

**Comment by 529834149** [comment]
谢谢 搞定了，返回的图片路径key名不正确  刚看了下源码 img_path = result.file_path;
